version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: imagehost-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=image_host
      - MYSQL_USER=imagehost
      - MYSQL_PASSWORD=imagehost_pass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_pass"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - appnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: imagehost-backend
    user: "root"
    environment:
      - PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=imagehost
      - DB_PASSWORD=imagehost_pass
      - DB_NAME=image_host
      - UPLOAD_PATH=/data/uploads
      - ALLOWED_TYPES=image/jpeg,image/png,image/gif,image/webp
    volumes:
      - uploads_data:/data/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: imagehost-web
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  mysql_data:
  uploads_data:

networks:
  appnet:
    driver: bridge